# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: APK Documentation 1.0.0
site_description: Documentation for WSO2 API Platform for Kubernetes
site_author: WSO2
site_url: https://apk.docs.wso2.com/en/latest/

# Repository
repo_name: wso2/apk
repo_url: https://github.com/wso2/apk
# Change the edit_url later when 1.0.0 is released
edit_uri: https://github.com/wso2/docs-apk/edit/main/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: WSO2 API Platform for Kubernetes - Documentation

# Configuration
theme:
    name: material
    custom_dir: theme/material
    logo: images/dummy-logo.svg # Real logo is coming from theme.
    favicon: images/favicon.png
    features:
        - content.code.copy
        - navigation.tabs
        - navigation.tabs.sticky
        - content.action.edit
        - content.action.view
        # - navigation.top
    language: 'en'
    palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
#Breaks build if there's a warning
comments: true
strict: false
# Navigation
nav:
    - Home: index.md
    - Get Started:
        #- Get Started - Overview: get-started/get-started-overview.md
        - Quick Start: get-started/quick-start-guide.md
        #- Basic Flow:
        #    - Overview: restapi/overview.md
        #    - Create an API: restapi/create-api.md
        #    - Discover Services: restapi/discover-your-services.md
        #    - Create an API Proxy:
        #        - From Scratch: develop-and-deploy-api/create-an-api-proxy/from-scratch.md
        #        - From an Existing Definition: develop-and-deploy-api/create-an-api-proxy/from-existing-definition.md
        #    - Test API: develop-and-deploy-api/test-api.md
        #    - Publish Your API: manage-apis/publish-your-api.md
    - API Management:
        - Develop and Deploy API:
           - Overview: create-api/create-api-overview.md
           - Create and deploy APIs:
                - K8s Native API Development: create-api/create-and-deploy-apis/create-api-using-cr.md
                - Enhanced API Development:
                    - Overview: create-api/create-and-deploy-apis/create-api-using-enhanced-flow.md
                    - Tools for Enhanced API Development: create-api/create-and-deploy-apis/tools-for-api-development.md
                    - Create and Deploy API:
                        - Generate APK Configuration file: create-api/create-and-deploy-apis/generate-apk-conf.md
                        - Generate K8s custom resources and Deploy: create-api/create-and-deploy-apis/create-and-deploy-api.md
                        - Direct Deploy into K8s Server: create-api/create-and-deploy-apis/direct-deploy.md
                        - Undeploy API: create-api/create-and-deploy-apis/direct-undeploy.md
                        - APK Config Language Support Plugin: create-api/create-and-deploy-apis/apk-conf-lang-support.md
        - Manage Endpoint:
            - Define Endpoints: develop-and-deploy-api/endpoints/prod-sand-endpoints.md
            - Manage Certificate: create-api/manage-service-endpoint/manage-certificate.md
            - Manage Security:
                - Via REST API: create-api/manage-service-endpoint/manage-security-via-rest-api.md
                - Via CR: create-api/manage-service-endpoint/manage-security-via-crs.md
            - Manage Resiliency:
                - Timeout: create-api/manage-service-endpoint/manage-resiliency-timeout.md
                - Retry Policy: create-api/manage-service-endpoint/manage-resiliency-retry-policy.md
                - Circuit Breaker: create-api/manage-service-endpoint/manage-resiliency-circuit-breaker.md
        - API Policies: 
            - Overview: create-api/create-and-attach-api-policies/api-policies-overview.md
            - Interceptors Service: 
                - Overview: create-api/create-and-attach-api-policies/interceptors/interceptors-overview.md
                - Via REST API: create-api/create-and-attach-api-policies/interceptors/interceptors-via-rest-api.md
                - Via CR: create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
            - Backend JWT Token Manipulation:
                - Via REST API: create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-rest-api.md
                - Via CR: create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-crs.md
            - CORS:
                - Via REST API: create-api/create-and-attach-api-policies/cors/enable-cors-via-rest-api.md
                - Via CR: create-api/create-and-attach-api-policies/cors/enable-cors-via-crs.md
        - Rate Limiting:
            - Overview: create-api/rate-limiting/rate-limiting-policy-overview.md
            - Simple Rate Limiting:
                - Via REST API: create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
                - Via CRs: create-api/rate-limiting/add-new-rate-limiting-policies-via-crs.md
            - Custom Rate Limiting: create-api/rate-limiting/custom-rate-limiting.md
        - API Security:
            - Generate Access Token: develop-and-deploy-api/security/generate-access-token.md
            - Authentication:
                - Enable API Security:
                    - OAuth2: develop-and-deploy-api/security/authentication/enable-api-security/oauth2.md
        - API Versions:
            - Create an API Version: develop-and-deploy-api/api-versions/create-an-api-versions.md
            - Default Version: develop-and-deploy-api/api-versions/default-version.md
            #- Backward Compatibility: develop-and-deploy-api/api-versions/backward-compatibility.md
        - API Properties: develop-and-deploy-api/api-properties/api-properties.md
        - API Scopes: develop-and-deploy-api/api-scopes/api-scopes.md
        - API Definition Endpoint: develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
        - Token Issuers: develop-and-deploy-api/token-issuers/token-issuers.md

    #                    - MTLS: develop-and-deploy-api/security/authentication/enable-api-security/mtls.md
    #                    - API Key: develop-and-deploy-api/security/authentication/enable-api-security/api-key.md
    #                    - Internal Key: develop-and-deploy-api/security/authentication/enable-api-security/internal-key.md
    #                - Disable API Security: develop-and-deploy-api/security/authentication/disable-api-security.md
    #            - Authorization:
    #                - Access Control for API Requests: develop-and-deploy-api/security/authorization/access-control-for-api-requests.md
    #    - Manage APIs:
    #       - API Documentation: manage-apis/api-documentation.md
    #       - Consumer Management:
    #           - Subscription Availability: manage-apis/consumer-management/subscription-availability.md
    #           - API Visibility: manage-apis/consumer-management/api-visibility.md
    #       - Usage Plans:
    #           - Add a New Rate Limiting Policy: manage-apis/usage-plans/add-a-new-rate-limiting-policy.md
    #           - Set Limits for Rate Limiting: manage-apis/usage-plans/set-limits-for-rate-limiting.md
    #       - Lifecycle Management:
    #           - API Lifecycle Overview: manage-apis/lifecycle-management/api-lifecycle-overview.md
    #           - Manage API Lifecycle: manage-apis/lifecycle-management/manage-api-lifecycle.md
    #           - Customize API Lifecycles: manage-apis/lifecycle-management/customize-api-lifecycles.md
    #           - Extending API Lifecycles: manage-apis/lifecycle-management/extending-api-lifecycles.md
    #       - Community Engagement:
    #           - Community URLs: manage-apis/community-engagement/community-urls.md
    #           - Share API Link: manage-apis/community-engagement/share-api-link.md
    #           - Comment on API: manage-apis/community-engagement/comment-on-api.md
    #       - API Categorization: manage-apis/api-categorization.md
    #       - API Monetization: manage-apis/api-monetization.md
    - Catalogs:
        - CRD Catalog: 
            - Overview - CRD Catalog: catalogs/kubernetes-crds.md
            - API: catalogs/crds/api_types.md
            - HTTPRoute: catalogs/samples/http-route.md
            - Authentication: catalogs/crds/authentication_types.md
            - Backend: catalogs/crds/backend_types.md
            - BackendJWT: catalogs/crds/backendjwt_types.md
            - APIPolicy: catalogs/crds/apipolicy_types.md
            - Interceptor Service: catalogs/crds/interceptorservice_types.md
                # - Overview: catalogs/api-policy.md
                # - CORS: catalogs/cors.md
                # - Interceptors: catalogs/interceptors.md
            - RateLimitPolicy: catalogs/crds/ratelimitpolicy_types.md
            # - Resolved JWT Issuer: catalogs/crds/resolvedJWTIssuer.md
            - Scope: catalogs/crds/scope_types.md
            - Token Issuer: catalogs/crds/tokenIssuer_types.md
                # - Overview: catalogs/rate-limit-policy.md
                # - API Level: catalogs/ratelimit-api.md
                # - Resource Level: catalogs/ratelimit-resource.md
                # - Custom: catalogs/ratelimit-custom.md
        - API Catalog:
            - Overview - API Catalog: catalogs/api-catalog.md
#            - Back Office APIs: catalogs/api-reference-back-office.md
            - Config Deployer APIs: catalogs/api-reference-config-deployer.md
            - Config Generator APIs: catalogs/api-reference-config-generator.md
#            - Developer Portal APIs: catalogs/api-reference-developer-portal.md
#            - Admin APIs: catalogs/api-reference-admin.md
        - Helm Configuration Catalog: catalogs/config-catalog.md
        - API Configuration Catalog: catalogs/apk-conf.md
    #   - CLI Catalog: catalogs/cli-reference.md
    #    - Helm Catalog: catalogs/config-catalog.md
    - Setup: 
        - Prerequisites: setup/prerequisites.md
        - Install: setup/install.md
        - Migration: setup/migration.md
        - Customize Configurations: setup/Customize-Configurations.md
#        - Organization: setup/organizations.md
       #- Deploy:
       #    - Deployment Patterns: get-started/dummy.md
       #    - All-in-one: get-started/dummy.md
       #    - Distributed:
       #        - Deployment Pattern 2: get-started/dummy.md
       #        - Deployment Pattern 3: get-started/dummy.md
       #- CI/CD: develop-and-deploy-api/ci-cd.md
        #- Customizations:
        #    - API Gateway - Enforcer:
            #    - Enforcer - Overview: apk-deck/enforcer-overview.md
        #        - Mediation Extensions:
        #            - Custom Filters: setup/customizations/gateway-enforcer/mediation-extensions/custom-filters.md
    - Administration:
        - Configure Identity Provider:
            - Overview: setup/identity-platform/idp/idp-overview.md
            - Non-production: setup/identity-platform/idp/non-production-idp.md
            - Asgardeo: setup/identity-platform/idp/asgardeo-idp.md
            - Auth0: setup/identity-platform/idp/auth0-idp.md
            - Any Third-party IdP: setup/identity-platform/idp/third-party-idp.md
        - Configure Analytics: 
            - Choreo Insights: setup/analytics/configure-analytics-for-choreo-insights.md
            - ELK Stack: setup/analytics/configure-analytics-for-elk-stack.md
        - Configure Listeners:
            - Configure Gateway Listeners: setup/listeners/configure-gateway-listeners.md
        - Configure Logs:
            - Overview: administration/configurations/configure-logs-overview.md
            - Adapter: administration/configurations/configure-logs-adapter.md
            - Enforcer: administration/configurations/configure-logs-enforcer.md
            - Router: administration/configurations/configure-logs-router.md
        - Configure Distributed Tracing: administration/distributed-tracing.md
        - Deploy in OpenShift: setup/deploy-in-openshift.md
    - About APK:
        - What is APK?: about-apk/what-is-apk.md
        - About This Release: about-apk/about-this-release.md
        - Architecture: about-apk/architecture.md
        - Performance Test Results: 
            - Overview: about-apk/performance-test-results/overview.md
            - Gateway router with one CPU: about-apk/performance-test-results/gateway-router-with-one-cpu.md
            - Gateway router with two CPUs: about-apk/performance-test-results/gateway-router-with-two-cpus.md
        - FAQs: about-apk/FAQs.md
       #- Key Concepts:
       #    - Key Concept 1: about-apk/key-concepts/key-concept.md
       #    - Key Concept 2: about-apk/key-concepts/key-concept.md
        # - WSO2 APK Deck:
            #- APK Deck Overview: apk-deck/overview.md
            #- API Gateway:
               #- API Gateway - Router:
               #    - Router - Overview: apk-deck/router-overview.md
               #    - Topic 1: get-started/dummy.md
               #    - Topic 2: get-started/dummy.md
                #- API Gateway - Enforcer:
                #    - Enforcer - Overview: apk-deck/enforcer-overview.md
                #   - Topic 2: get-started/dummy.md
           #- Back Office: 
           #    - Back Office Overview: apk-deck/back-office-overview.md
           #    - Access: get-started/dummy.md
           #    - Topic 1: get-started/dummy.md
           #    - Topic 2: get-started/dummy.md
           #    - GraphQL: 
           #        - Test API: develop-and-deploy-api/test-graphql-api.md
           #    - WebSocket:
           #        - Test API: develop-and-deploy-api/test-websocket-api.md
           #    - SOAP:
           #        - Test API: develop-and-deploy-api/test-soap-api.md
           #- Runtime:
           #    - Runtime Overview: apk-deck/runtime-overview.md
           #    - Access: get-started/dummy.md
           #    - Topic 1: get-started/dummy.md
           #    - Topic 2: get-started/dummy.md
           #- Developer Portal:
           #    - Developer Portal - Overview: get-started/dummy.md
           #    - Access: get-started/dummy.md
           #    - Topic 1: get-started/dummy.md
           #    - Topic 2: get-started/dummy.md
           #- Admin Portal:
           #    - Admin Portal - Overview: get-started/dummy.md
           #    - Access: get-started/dummy.md
           #    - Topic 1: get-started/dummy.md
           #    - Topic 2: get-started/dummy.md
        #- Product Pitch: https://wso2.com/api-manager
    - Reach Out:
        - Community: reachout/community.md # Brief description and links to Discord and Stack OverFlow
        - Support: https://wso2.com/subscription/#support
        #- Report Bugs: get-started/dummy.md # Brief description and links to Git links for doc issues and product issues
        - Training and Certification: https://wso2.com/training/
        - Resources: https://wso2.com/library/

# Extensions
markdown_extensions:
    # - pymdownx.highlight:
    #     anchor_linenums: true
    #     line_spans: __span
    #     pygments_lang_class: true
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - markdown.extensions.admonition
    # - markdown.extensions.codehilite:
    #       linenums: true
    #       use_pygments: false
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
          permalink: true
    - markdown_include.include:
          base_path: docs
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.snippets:
          base_path: docs
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - search
    - markdownextradata: {}
    - exclude:
          glob:
              - wip/*
    #- redirects:
    #      redirect_maps:

    # Extra
extra_css:
    # You can select a different theme for syntax highlighting by simply 
    # selecting a different css file file bellow from the available list.
    - assets/lib/highlightjs/styles/vs.min.css
    # Make sure to activate only one palette at a time.
    # If all the palettes are commented out, the default material theme palette will take over
    - assets/css/blue-palette-alt1.css
    # - assets/css/blue-palette-alt2.css
    # - assets/css/blue-palette.css
    # - assets/css/green-palette.css
    # - assets/css/orange-palette.css
    - assets/css/apktheme.css
    - assets/lib/json-formatter/json-formatter.css
    - assets/css/config-catalog.css
    - assets/lib/fontawesome-free-6.3.0-web/css/all.min.css
    - assets/css/redoc.css
extra_javascript:
    - assets/lib/highlightjs/highlight.min.js
    - assets/lib/json-formatter/json-formatter.umd.js
    - assets/js/apktheme.js
    # - assets/lib/backtotop/js/util.js
    # - assets/lib/backtotop/js/main.js

extra:
    social:
        - type: github
          link: https://github.com/wso2
        - type: twitter
          link: https://twitter.com/wso2
        - type: linkedin
          link: https://www.linkedin.com/company/wso2
    site_version: 1.0.0
    # base_path: http://localhost:8000
    base_path: https://apk.docs.wso2.com
    envoy_path: https://www.envoyproxy.io/docs/envoy/v1.20.0
# static_cache_control: "no-cache"
